# Generated by Django 5.1.2 on 2024-11-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_shopping_products_shopping_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(to='shop.flower2')),
            ],
        ),
        migrations.DeleteModel(
            name='Shopping',
        ),
    ]
