# Generated by Django 5.1.2 on 2024-11-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shopping2_delete_shopping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopping2',
            new_name='Shopping_now',
        ),
    ]
