# Generated by Django 5.1.2 on 2024-11-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_shopping_now_shopping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Select_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(to='shop.flower2')),
            ],
        ),
        migrations.DeleteModel(
            name='Shopping',
        ),
    ]
